# Generated by Django 4.0.4 on 2022-05-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
