# Generated by Django 4.0.4 on 2022-05-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_country_profile_province_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='farmer',
            field=models.BooleanField(default=False),
        ),
    ]
