# Generated by Django 4.0.4 on 2022-05-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_profile_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='farmer',
            new_name='isFarmer',
        ),
        migrations.AddField(
            model_name='profile',
            name='wantMarketingEmails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='wantPromoEmails',
            field=models.BooleanField(default=False),
        ),
    ]
