# Generated by Django 4.0.4 on 2022-06-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_farmer_profile_isfarmer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('Measure', models.CharField(choices=[(1, 'Gr'), (2, 'Kg')], default='GR', max_length=2)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productcategories')),
            ],
        ),
    ]
