# Generated by Django 4.0.4 on 2022-06-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_productcategories_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategory',
        ),
    ]
