# Generated by Django 4.0.4 on 2022-06-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_products_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Measure',
            field=models.CharField(choices=[('Gr', 'Gr'), ('Kg', 'Kg')], default='GR', max_length=2),
        ),
    ]
