# Generated by Django 4.0.4 on 2022-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_product_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Measure',
            field=models.CharField(choices=[('Gr', 'Gr'), ('Kg', 'Kg'), ('Btl', 'Btl')], default='GR', max_length=3),
        ),
    ]
