# Generated by Django 4.0.4 on 2022-06-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_product_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Picture',
            field=models.CharField(default='/static/shop/img/product/product-1.jpg', max_length=200),
        ),
    ]
