# Generated by Django 4.0.4 on 2022-07-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='businessName',
            field=models.CharField(default='N/A', max_length=32),
        ),
    ]
